on:
  workflow_dispatch:

jobs:
  get_s3_buckets:
    name: Get S3 Buckets
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Configure AWS Credentials" Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsAccess-Role-O9i0CepFbbvf
          aws-region: eu-west-1
      - name: List the S3 buckets
        run: |
          aws s3 ls